---
# Source: wasmcloud-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasmcloud-operator
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: wasmcloud-operator/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasmcloud-operator
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - configmaps
      - serviceaccounts
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
  - apiGroups:
      - k8s.wasmcloud.dev
    resources:
      - wasmcloudhostconfigs
      - wasmcloudhostconfigs/status
    verbs:
      - "*"
---
# Source: wasmcloud-operator/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasmcloud-operator
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wasmcloud-operator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: wasmcloud-operator
    namespace: default
---
# Source: wasmcloud-operator/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasmcloud-operator-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: wasmcloud-operator
    namespace: default
---
# Source: wasmcloud-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wasmcloud-operator
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
---
# Source: wasmcloud-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmcloud-operator
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wasmcloud-operator
      app.kubernetes.io/instance: wasmcloud-operator
  template:
    metadata:
      labels:
        helm.sh/chart: wasmcloud-operator-0.1.5
        app.kubernetes.io/name: wasmcloud-operator
        app.kubernetes.io/instance: wasmcloud-operator
        app.kubernetes.io/version: "0.4.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: wasmcloud-operator
      securityContext:
        {}
      containers:
        - name: wasmcloud-operator
          securityContext:
            {}
          image: "ghcr.io/wasmcloud/wasmcloud-operator:0.4.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: info,async_nats=error
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            {}
---
# Source: wasmcloud-operator/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "wasmcloud-operator-test-connection"
  labels:
    helm.sh/chart: wasmcloud-operator-0.1.5
    app.kubernetes.io/name: wasmcloud-operator
    app.kubernetes.io/instance: wasmcloud-operator
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: alpine
      command: ['wget']
      args: ['--no-check-certificate', 'https://wasmcloud-operator:8443/apis/core.oam.dev/v1beta1']
  restartPolicy: Never
