---
# Source: wadm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wadm
  labels:
    helm.sh/chart: wadm-0.2.3
    app.kubernetes.io/name: wadm
    app.kubernetes.io/instance: wadm
    app.kubernetes.io/version: "v0.12.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app.kubernetes.io/name: wadm
      app.kubernetes.io/instance: wadm
  template:
    metadata:
      labels:
        helm.sh/chart: wadm-0.2.3
        app.kubernetes.io/name: wadm
        app.kubernetes.io/instance: wadm
        app.kubernetes.io/version: "v0.12.2"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: wadm
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/wasmcloud/wadm:v0.12.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: WADM_NATS_SERVER
              value: "nats.default.svc.cluster.local:4222"
            
          resources:
            {}
