apiVersion: k8s.wasmcloud.dev/v1alpha1
kind: WasmCloudHostConfig
metadata:
  name: wasmcloud-host
spec:
  lattice: default
  # version: "1.1.1"
  version: "1.0.4"
  hostLabels:
    cluster-type: kind
  # registryCredentialsSecret: "regcred"
